### ISSUE TITLE
I have no idea what I'm doing

### ISSUE THREAD

**Issue by nateabele** [nateabele/jsengine#1]
![I have no idea what I'm doing](https://imgs.search.brave.com/uXpGPUxUIZKtqMDNlsKI_YR-ZZPqKt6TpPVrdh8Qe-M/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS50ZW5vci5jb20v/V2ZqM0dRb1BfOWdB/QUFBQy9pLWhhdmUt/bm8taWRlYS13aGF0/LWltLWRvaW5nLXNw/YWNlLWRvZy5naWY.gif)

@scrogson Hey! [I tried hitting you up on Twitter the other day](https://twitter.com/nateabele/status/1726116423423099112).

So, this is literally my first Rust project that isn't copypasta from a hello world tutorial. 🤣  It's also my first public Elixir code.

Anyway, I have no idea what to do next... should I publish to Hex? Is the code sane enough to publish to Hex? Is it any good? Where should I see if this is something people are interested in / is worth publishing? Am I violating community norms with my naming conventions??

I could use a sanity check if you've got an extra 10 minutes—because _I have no what what I'm doing_.

Feel free to point me in the right direction if there's a good resource on this.

Thanks man!

**Comment by scrogson** [comment]
@nateabele Hey! It's been a while. I hope you're doing well. Let me dig in and see what feedback I can give you.

**Comment by nateabele** [comment]
> I hope you're doing well.

Likewise! I'm well, thanks. And thanks for your work on Rustler. It's far and away the cleanest and most elegant FFI I've ever worked with.

> Let me dig in and see what feedback I can give you.

Appreciated muchly, sir. This is actually my first OS thing in a few years, so I'm totally out of the loop (hence part of why I was like... help!)—feels good to get back in the game though.

**Comment by Joshwani** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Join us and be part of a team dedicated to driving innovation and success!

## How to Apply:
To apply for this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.cainky, @gyroflaw, @mzhao8, @aluminum-mistress, @lyh1001, @andromedhaaw, @vernehar, @heyskylark, @blockchain-develop, @doggeddog, @hugodemenez, @ivanzud, @sahadcp7, @tarik0, @x1hy9, @jusonalien, @blokboy, @toriving, @MSloyan, @misszar1996
